#!/bin/bash
# PostgreSQL SSL setup script
# This script generates SSL certificates and is called AFTER database initialization

set -e

echo "🔐 Setting up PostgreSQL SSL configuration..."

# This script runs after the main database initialization
# The PGDATA directory should already exist and be initialized

PGDATA="${PGDATA:-/var/lib/postgresql/data}"
SSL_DIR="/var/lib/postgresql/ssl"

# Create SSL directory
mkdir -p "$SSL_DIR"

# Generate SSL certificates
echo "📝 Generating SSL certificates..."
cd "$SSL_DIR"

# Generate private key
openssl genrsa -out server.key 2048
chmod 600 server.key
chown postgres:postgres server.key

# Generate self-signed certificate (valid for 365 days)
openssl req -new -x509 -key server.key -out server.crt -days 365 \
    -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"
chmod 644 server.crt
chown postgres:postgres server.crt

# Create a simple SSL configuration that appends to postgresql.conf
echo "📝 Configuring PostgreSQL for SSL..."

# Check if SSL is already configured
if ! grep -q "ssl = on" "$PGDATA/postgresql.conf"; then
    cat >> "$PGDATA/postgresql.conf" << 'EOF'

# SSL Configuration - Added by setup-ssl.sh
ssl = on
ssl_cert_file = '/var/lib/postgresql/ssl/server.crt'
ssl_key_file = '/var/lib/postgresql/ssl/server.key'
EOF
    echo "✅ SSL configuration added to postgresql.conf"
else
    echo "ℹ️ SSL already configured in postgresql.conf"
fi

# Update pg_hba.conf to support both SSL and non-SSL connections
echo "📝 Updating pg_hba.conf for SSL support..."
cat > "$PGDATA/pg_hba.conf" << 'EOF'
# PostgreSQL Client Authentication Configuration File
# Generated by setup-ssl.sh

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
hostssl all             all             127.0.0.1/32            md5
hostssl all             all             0.0.0.0/0               md5

# IPv6 local connections:
hostssl all             all             ::1/128                 md5

# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
hostssl replication     all             127.0.0.1/32            md5
hostssl replication     all             ::1/128                 md5

# Allow SSL connections from any host
hostssl all             all             all                     md5

EOF

# Set proper ownership for configuration files
chown postgres:postgres /var/lib/postgresql/data/postgresql.conf
chown postgres:postgres /var/lib/postgresql/data/pg_hba.conf

echo "✅ SSL setup completed successfully!"
echo "🔐 PostgreSQL is now configured to require SSL connections"
echo "📋 SSL files created:"
echo "   - Private key: /var/lib/postgresql/ssl/server.key"
echo "   - Certificate: /var/lib/postgresql/ssl/server.crt"
echo "   - Config: /var/lib/postgresql/data/postgresql.conf"
echo "   - Auth: /var/lib/postgresql/data/pg_hba.conf"