#!/bin/bash
# PostgreSQL SSL setup script
# This script generates SSL certificates and configures PostgreSQL for SSL connections

set -e

echo "🔐 Setting up PostgreSQL SSL configuration..."

# Create SSL directory
SSL_DIR="/var/lib/postgresql/ssl"
mkdir -p "$SSL_DIR"
cd "$SSL_DIR"

# Generate private key
echo "📝 Generating SSL private key..."
openssl genrsa -out server.key 2048
chmod 600 server.key
chown postgres:postgres server.key

# Generate certificate signing request
echo "📝 Generating certificate signing request..."
openssl req -new -key server.key -out server.csr -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"

# Generate self-signed certificate (valid for 365 days)
echo "📝 Generating self-signed certificate..."
openssl x509 -req -in server.csr -signkey server.key -out server.crt -days 365
chmod 644 server.crt
chown postgres:postgres server.crt

# Clean up CSR file
rm server.csr

# Create custom postgresql.conf with SSL enabled
echo "📝 Creating PostgreSQL configuration with SSL enabled..."
cat > /var/lib/postgresql/data/postgresql.conf << 'EOF'
# PostgreSQL configuration with SSL support
# Generated by setup-ssl.sh

#------------------------------------------------------------------------------
# CONNECTIONS AND AUTHENTICATION
#------------------------------------------------------------------------------

listen_addresses = '*'
port = 5432
max_connections = 200

# SSL Configuration
ssl = on
ssl_cert_file = '/var/lib/postgresql/ssl/server.crt'
ssl_key_file = '/var/lib/postgresql/ssl/server.key'
ssl_ca_file = ''
ssl_crl_file = ''
ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL'
ssl_prefer_server_ciphers = on
ssl_ecdh_curve = 'prime256v1'
ssl_min_protocol_version = 'TLSv1.2'
ssl_max_protocol_version = ''

#------------------------------------------------------------------------------
# RESOURCE USAGE (except WAL)
#------------------------------------------------------------------------------

shared_buffers = 256MB
effective_cache_size = 1GB
maintenance_work_mem = 64MB
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200

#------------------------------------------------------------------------------
# WRITE AHEAD LOG
#------------------------------------------------------------------------------

wal_level = replica
max_wal_senders = 3
max_replication_slots = 3

#------------------------------------------------------------------------------
# ERROR REPORTING AND LOGGING
#------------------------------------------------------------------------------

log_destination = 'stderr'
logging_collector = on
log_directory = 'log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_truncate_on_rotation = off
log_rotation_age = 1d
log_rotation_size = 10MB
log_min_messages = info
log_min_error_statement = error
log_min_duration_statement = -1
log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_statement = 'none'
log_temp_files = -1
log_timezone = 'UTC'

#------------------------------------------------------------------------------
# CLIENT CONNECTION DEFAULTS
#------------------------------------------------------------------------------

datestyle = 'iso, mdy'
timezone = 'UTC'
lc_messages = 'en_US.utf8'
lc_monetary = 'en_US.utf8'
lc_numeric = 'en_US.utf8'
lc_time = 'en_US.utf8'
default_text_search_config = 'pg_catalog.english'

#------------------------------------------------------------------------------
# LOCK MANAGEMENT
#------------------------------------------------------------------------------

deadlock_timeout = 1s
max_locks_per_transaction = 64
max_pred_locks_per_transaction = 64

EOF

# Create custom pg_hba.conf with SSL requirements
echo "📝 Creating pg_hba.conf with SSL configuration..."
cat > /var/lib/postgresql/data/pg_hba.conf << 'EOF'
# PostgreSQL Client Authentication Configuration File
# Generated by setup-ssl.sh

# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust

# IPv4 local connections:
hostssl all             all             127.0.0.1/32            md5
hostssl all             all             0.0.0.0/0               md5

# IPv6 local connections:
hostssl all             all             ::1/128                 md5

# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
hostssl replication     all             127.0.0.1/32            md5
hostssl replication     all             ::1/128                 md5

# Allow SSL connections from any host
hostssl all             all             all                     md5

EOF

# Set proper ownership for configuration files
chown postgres:postgres /var/lib/postgresql/data/postgresql.conf
chown postgres:postgres /var/lib/postgresql/data/pg_hba.conf

echo "✅ SSL setup completed successfully!"
echo "🔐 PostgreSQL is now configured to require SSL connections"
echo "📋 SSL files created:"
echo "   - Private key: /var/lib/postgresql/ssl/server.key"
echo "   - Certificate: /var/lib/postgresql/ssl/server.crt"
echo "   - Config: /var/lib/postgresql/data/postgresql.conf"
echo "   - Auth: /var/lib/postgresql/data/pg_hba.conf"